; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
lib_deps = 
	ArduinoJson
	FS
build_flags = 
	-w
	-Os
	-DTFT
	-fpermissive

[env:cyd]
lib_deps =
  ArduinoJson
  lvgl/lvgl@^9.1.0
  bodmer/TFT_eSPI@^2.5.34
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  knolleary/PubSubClient@^2.8
  miwagner/ESP32CAN@^0.0.1
  robtillaart/ADS1X15@^0.5.0
  robtillaart/INA226@^0.6.0
monitor_speed = 115200
build_src_filter =
  +<*>
  -<TFT_Display/>
  -<.git/>
  -<.svn/>

build_flags =
	-Iinclude
	-DLV_CONF_SKIP
	-DUSE_LVGL
	-DILI9341_2_DRIVER
	-DTFT_BL=21
  	-DLV_USE_TFT_ESPI
	-DLV_FONT_MONTSERRAT_20
	-DLV_FONT_MONTSERRAT_28
	-DUSER_SETUP_LOADED
	-DUSE_HSPI_PORT
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1

  	-DXPT2046_IRQ=36
  	-DXPT2046_MOSI=32
  	-DXPT2046_MISO=39
  	-DXPT2046_CLK=25
  	-DXPT2046_CS=33

	; for cn5
	;-DI2C_SDA=22
	;-DI2C_SCL=27

	-DRXD2=22
	-DTXD2=27

	;for miss unng sdcard
	-DI2C_SDA=23
	-DI2C_SCL=5
	
	
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=55000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=1500000


